Recover hormud data
AfricasVoices/Project-ADSS pull request #83
Opened 2019-05-10 13:29 UTC by as2388

Review #79 first.

Not sure if I should merge this given that the project finished without incorporating the recovered Hormud data into the analysis file used in the report, but this PR at least shows how data recovery can be done.

2019-05-15 18:24 UTC, lukechurch commented
@as2388 Maybe we could tag the release that was used to produce the final analysis file?

2019-06-07 20:44 UTC, lukechurch commented
@as2388 Please could you address the conflicts and request a review again?

2019-06-07 20:44 UTC, lukechurch requested changes
conflicts

2019-06-11 14:37 UTC, as2388 commented
@lukechurch conflicts resolved

2019-06-17 20:55 UTC, lukechurch approved these changes
Thanks @as2388

2019-06-17 20:55 UTC, lukechurch commented on run_scripts/2_fetch_data.sh
> +    echo "Fetches all the raw data from Rapid Pro and from the Shaqadoon recovery CSVS, and converts to TracedData"
nit: CSVs

2019-06-17 20:55 UTC, lukechurch commented on generate_outputs.py
> +            raw_recovery_path = f"{raw_data_dir}/{recovery_csv_url.split('/')[-1].split('.')[0]}.json"
this feels a bit unpleasant, but it also doesn't feel worth a different structural solution.

2019-06-18 14:23 UTC, merged